# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1944f912b3a5de2b6c0ec6998cc7dbf28ec9b7e99c5d6536c9b10d1b68228b77f14bd7dbd9139753e52091cd7ecfddbeaba65d75cd6fa303fcd46d54744ab7e4

test:
  secret_key_base: ade1bbe67aedf5fbca392126c67871cb574953ae18f3d191b13b57c0d78c0c8ed683130f64abd78e133a5951c0aa721a27f5271c97c1edb1c9d32d9189426e1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
